### ISSUE TITLE
18.03.2016 Acil Yapılacaklar

### ISSUE THREAD

**Issue by FatihErdem** [YouReads/YouReads#101]
Bir sonraki aşamada yapılması planlanan issuelar şunlar:
- [x] #55 Sadece admin duyuru girebilmeli
- [ ] #10 Detaylı istatistik sayfası
- [ ] #76 Sorunlara sebep oluyor nedenlerin bilinmemesi
- [x] #45 Yorumlarda 2 enter kısıtı
- [x] #28 Başlık altında benimkiler sekmesi
- [x] #14 Profil sayfasında yazar tarafından açılmış başlıkların görünmesi
- [x] #3 Anlık mesaj ve takip ışığı
- [ ] #102  Tema sıfırlanma bugı
- [ ] #75 Yazar, sanatçı vs. isimleri küçük yazilsin
- [x] #67 Begeni butonlarinin renklendirilmesi

**Comment by FatihErdem** [comment]
#28 tamamlandi.

**Comment by canarslan12** [comment]
#45 tamamlandı
