### ISSUE TITLE
14.03.2016 Acil Yapılacaklar

### ISSUE THREAD

**Issue by FatihErdem** [YouReads/YouReads#78]
Acil olarak eklenmesi düşünülen özellikler şunlar
- [x] #61 Versiyon sayfası olmalı. Şu andan itibaren eklediklerimizi detaylıca orada açıklamalıyız.
- [x] #8 Bugün eklenecek bir çok ayar buraya eklenecek. Ondan dolayı şart.
- [x] #77 Başlık ve kanal engelleme
- [x] #50 Bir öncekiyle bağlantılı. Devam niteliğinde madde.

Bundan sonrakiler halihazırda eklentide yapılmış durumda. Tartışılıp eklenebilir.
- [x] #6 Takipte başlığın en üste çıkması
- [x] #7 Sağ öneri kısmının açılıp kapanabilmesi
- [x] #5 Tema sıfırlanma durumu. Eklentide de tam olarak çözülemedi. İlk açıldığında gene ayar kısmında gündüzdeymiş gibi görünüyor.
- [x] #17 Editleme tarihinin de yazması
- [x] #48 Mobil kısmı hariç zaten eklentide var.
- [x] #11 Ctrl+Enter ile yorum gonderilmesi
- [x] #12 Baslığa tıklanınca Bugün ya da Gündemde açılması

**Comment by FatihErdem** [comment]
@anilari @canarslan12 @kodbilenadam @abiyoureads

**Comment by FatihErdem** [comment]
#8 oncelikli su anda. Basit bir Gelimis Ayar sekmesinden sonra geri kalanlar hizlica eklenecek.

**Comment by FatihErdem** [comment]
#8 #77 #50 @canarslan12 tarafindan tamamlandi.

**Comment by FatihErdem** [comment]
#7 @canarslan12  tarafindan tamamlandi.

**Comment by FatihErdem** [comment]
#12 dolayli yollardan yapildi. Sol framede bugun secilirse bugunde acilacak.
